services:
  postgres-db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_money
      PGPORT: 4444
    ports:
      - "4444:4444"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
